# Generated by Django 4.1.3 on 2022-11-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='gmat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
