# Generated by Django 4.1.3 on 2022-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_university_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
