# Generated by Django 4.1.3 on 2022-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_university_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='fee_waiver',
            field=models.CharField(blank=True, choices=[('Available', 'Available'), ('Not Available', 'Not Available'), ('No info', 'No info')], max_length=100, null=True),
        ),
    ]
