# Generated by Django 4.1.3 on 2022-11-21 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_university_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gre', models.IntegerField()),
                ('toefl', models.IntegerField()),
                ('sop', models.FloatField()),
                ('lor', models.FloatField()),
                ('gpa', models.FloatField()),
                ('admit_chance', models.FloatField()),
                ('research', models.CharField(choices=[('0', '0'), ('1', '1')], max_length=20)),
                ('rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=20)),
            ],
        ),
    ]
