# Generated by Django 4.1.3 on 2022-11-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_admission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='public',
            new_name='program_rank_region',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='qs',
            new_name='program_rank_state',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='us',
            new_name='program_rank_world',
        ),
        migrations.AddField(
            model_name='university',
            name='city_living_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='qs_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='university',
            name='region_rank',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.')], max_length=100, null=True),
        ),
    ]
