# Generated by Django 4.1.3 on 2022-12-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='admission_req',
        ),
        migrations.RemoveField(
            model_name='university',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='university',
            name='program_rank_region',
        ),
        migrations.RemoveField(
            model_name='university',
            name='program_rank_state',
        ),
        migrations.RemoveField(
            model_name='university',
            name='program_rank_world',
        ),
        migrations.RemoveField(
            model_name='university',
            name='region_rank',
        ),
        migrations.AddField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US'), ('UK', 'UK'), ('non-EU', 'non-EU')], max_length=100, null=True),
        ),
    ]
