# Generated by Django 4.1.3 on 2022-12-04 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_remove_university_admission_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.'), ('Exchange programme', 'Exchange programme'), ('Training programme', 'Training programme')], max_length=100, null=True),
        ),
    ]
