# Generated by Django 4.1.5 on 2023-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_alter_blogs_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='category',
            field=models.CharField(blank=True, choices=[('Sport', 'Sport'), ('Movie', 'Movie'), ('News', 'News'), ('Climate', 'Climate')], max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
