# Generated by Django 4.1.5 on 2023-02-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0019_alter_blogs_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=50)),
                ('amount', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('eligibility', models.TextField()),
                ('benefits', models.TextField()),
                ('dedline', models.DateField()),
                ('link', models.CharField(max_length=300)),
            ],
        ),
    ]
