# Generated by Django 4.1.5 on 2023-02-12 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0020_scholarship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='dedline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
