# Generated by Django 4.1.5 on 2023-02-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0021_alter_scholarship_dedline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='dedline',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
