# Generated by Django 4.1.5 on 2023-02-12 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0023_alter_scholarship_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scholarship',
            old_name='eligibility',
            new_name='eligibity',
        ),
    ]
