# Generated by Django 4.1.5 on 2023-02-18 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0024_rename_eligibility_scholarship_eligibity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US'), ('UK', 'UK'), ('non-EU', 'non-EU')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('PHD', 'PHD'), ('Exchange programme', 'Exchange programme'), ('Training programme', 'Training programme')], max_length=100, null=True),
        ),
    ]
