# Generated by Django 4.1.5 on 2023-02-19 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0026_remove_contact_name_remove_contact_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='number',
        ),
    ]
