# Generated by Django 4.1.5 on 2023-03-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0029_alter_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admission',
            name='admit_chance',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gpa',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='gre',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='lor',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='research',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='sop',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='toefl',
        ),
        migrations.AddField(
            model_name='admission',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='degree',
            field=models.CharField(blank=True, choices=[('Bachelor', 'Bachelor'), ('Master', 'Master'), ('Ph.D.', 'Ph.D.'), ('Exchange programme', 'Exchange programme'), ('Training programme', 'Training programme')], max_length=100, null=True),
        ),
    ]
