# Generated by Django 4.1.5 on 2023-03-07 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0030_remove_admission_admit_chance_remove_admission_gpa_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admission',
            new_name='Apply',
        ),
    ]
