# Generated by Django 4.1.5 on 2023-03-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0031_rename_admission_apply'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='study_field',
            field=models.CharField(blank=True, choices=[('Business Management', 'Business Management'), ('Economics', 'Economics'), ('Social Sciences', 'Social Sciences'), ('Finance & Accounting', 'Finance & Accounting')], max_length=100, null=True),
        ),
    ]
