# Generated by Django 4.1.5 on 2023-03-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0032_university_study_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholarship',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US'), ('non-EU', 'non-EU')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='region',
            field=models.CharField(blank=True, choices=[('EU', 'EU'), ('US', 'US'), ('non-EU', 'non-EU')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='university',
            name='study_field',
            field=models.CharField(blank=True, choices=[('Business Management', 'Business Management'), ('Economics', 'Economics'), ('Social Sciences', 'Social Sciences'), ('Finance & Accounting', 'Finance & Accounting'), ('Physics', 'Physics'), ('Engineering', 'Engineering'), ('Analytics', 'Analytics'), ('Archaeology', 'Archaeology'), ('Chemistry', 'Chemistry'), ('Science', 'Science'), ('Computer Sciences', 'Computer Sciences'), ('Biology', 'Biology'), ('Astronomy', 'Astronomy'), ('Medicine', 'Medicine'), ('Informatics', 'Informatics'), ('Health', 'Health'), ('Biotechnology', 'Biotechnology'), ('Management', 'Management'), ('Nutrition', 'Nutrition'), ('Architecture', 'Architecture'), ('Technologies', 'Technologies'), ('Mechatronics', 'Mechatronics'), ('Technology', 'Technology'), ('Nanotechnologies', 'Nanotechnologies'), ('Bioengineering', 'Bioengineering'), ('Biomechanics', 'Biomechanics'), ('Design', 'Design'), ('Robotics', 'Robotics'), ('Systems', 'Systems'), ('Logistics', 'Logistics'), ('Nanobiotechnology', 'Nanobiotechnology'), ('Diagnostics', 'Diagnostics'), ('Cryptography', 'Cryptography'), ('Manufacturing', 'Manufacturing'), ('Nursing', 'Nursing'), ('Education', 'Education'), ('Arts', 'Arts'), ('Geography', 'Geography'), ('Mathematics', 'Mathematics'), ('Agriculture', 'Agriculture'), ('Geoinformatics', 'Geoinformatics'), ('Analysis', 'Analysis'), ('Economy', 'Economy'), ('Transport', 'Transport'), ('Industry', 'Industry'), ('Archeology', 'Archeology'), ('Studies', 'Studies'), ('Dietetics', 'Dietetics'), ('Sciences', 'Sciences'), ('Midwifery', 'Midwifery'), ('Training', 'Training'), ('Physiotherapy', 'Physiotherapy'), ('Telecommunication', 'Telecommunication')], max_length=100, null=True),
        ),
    ]
