# Generated by Django 4.1.5 on 2023-03-08 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0033_alter_scholarship_region_alter_university_region_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apply',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='apply',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apply',
            name='number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='apply',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
