# Generated by Django 4.1.5 on 2023-03-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0034_rename_name_apply_first_name_apply_last_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='dedline',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='tutaion_fee',
            new_name='tution_fee',
        ),
    ]
