# Generated by Django 4.1.5 on 2023-03-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0037_apply_program'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='gpa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
